services:
    server:
        build: .
        env_file:
            - .env
        ports:
            - "3000:3000"
        volumes:
            - ./uploads:/app/uploads  # Mount uploads folder để lưu avatar
